### ISSUE TITLE
Load model checkpoints

### ISSUE THREAD

**Issue by avidkenil** [NYU-CDS-Capstone-Project/learning_visual_embeddings#2]
Load the model checkpoints and resume training/do the evaluation with the given model checkpoint.

**Comment by ranamihir** [comment]
- Added `load-ckpt` argument which takes name of checkpoint file to load
- Added support for multiple GPUs:
    - state dicts are always stored by moving `network` to a single GPU (`nn.DataParallel(network).module`)
    - set number of threads set to 1 to avoid multiprocessing error with KeyboardInterrupt
